import type { Metadata } from "next";
import { Hind_Siliguri, Poppins, Roboto } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Griipbuddy",
  description: "Generated by create next app",
};

const hind_siliguri = Hind_Siliguri({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "bengali", "latin-ext"],
  variable: "--font-bangla",
});

const roboto = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "symbols"],
  variable: "--font-english",
});
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-poppins",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hind_siliguri.variable} ${poppins.variable} ${roboto.variable} ${hind_siliguri.className} antialiased`}
      >
        <h2>Hello world</h2>
      </body>
    </html>
  );
}
